# -*- coding: utf-8 -*-
"""add_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xy6S6m8rgiHZjz9ciIn_pkpbwKbskR_S
"""

import skimage as ski
import numpy as np
import matplotlib.pyplot as plt

import math

"""## Importation des images"""

from google.colab import drive
drive.mount('/content/drive/')

path = 'drive/MyDrive/Colab Notebooks/BIP/'
tile = ski.io.imread(f'{path}tiles/tile_1.tif')
mask = ski.io.imread(f'{path}masks/mask_1.tif')

tile.shape, mask.shape

"""## Indicies calculation"""

tile.shape

red = tile[:,:,0]
green = tile[:,:,1]
blue = tile[:,:,2]
NIR = tile[:,:,3]

brightness = (red + green + blue + NIR) / 4

NDVI = (NIR-red/NIR+red)
EVI = 2.5*((NIR-red)/(NIR+6*red-7.5*blue+1))
SAVI = ((1+0.5)*(NIR-red))/(NIR+red+0.5)

"""## Other features from skimage"""

gray_tile = ski.color.rgb2gray(tile[:,:,0:3])
gray_tile.shape

blob_dog = ski.feature.blob_dog(gray_tile, min_sigma=70, max_sigma=200 ,threshold=0.1) # difference of gaussian

blob_doh = ski.feature.blob_doh(gray_tile, max_sigma=100 ,threshold=1 ) # determinant of Hessian
blob_log = ski.exposure.equalize_hist(gray_tile) ## for better blob log
blob_log = ski.feature.blob_log(gray_tile, max_sigma=100 ,threshold=1)  # laplacian of gaussian
canny = ski.feature.canny(gray_tile)  # edge filter

canny.shape, brightness.shape
canny = np.clip(canny, 1e-5, None)  # Replace 0 with a very small number

TDGI = -np.log10(canny)*brightness

blob_dog.shape

fig, ax = plt.subplots(1,2)
ax[0].imshow(tile[:,:,0:3])
ax[0].title.set_text('blob DoG (difference of gaussian)')
for blob in blob_dog:
    y, x, r = blob
    c = plt.Circle((x, y), r, linewidth=2, fill=False)
    ax[0].add_patch(c)
ax[1].imshow(TDGI, cmap="gray")
ax[1].title.set_text("TGDI")

fig,ax = plt.subplots(1,3)
ax[0].imshow(blob_dog, cmap="gray")
ax[1].imshow(blob_doh, cmap="gray")
ax[2].imshow(blob_log, cmap="gray")

ax[0].title.set_text("dog")
ax[1].title.set_text("doh")
ax[2].title.set_text("log")

dog = ski.filters.difference_of_gaussians(tile,2, 10)
edge_robert = ski.filters.roberts(gray_tile)
edge_sobel = ski.filters.sobel(gray_tile)
edge_scharr = ski.filters.scharr(gray_tile)
edge_prewitt = ski.filters.prewitt(gray_tile)

dog.shape

daisy_desc, daisy = ski.feature.daisy(gray_tile, visualize=True)  # feature descriptor similar to SIFT

gray_tile_scaled = (gray_tile * 3).astype(np.uint8)
glcm = ski.feature.graycomatrix(gray_tile_scaled, [1], [0, np.pi/4, np.pi/2, 3*np.pi/4], levels=4)
glcm[:, :, 0, 1]

contrast = ski.feature.graycoprops(glcm, 'contrast')
dissimilarity = ski.feature.graycoprops(glcm, 'dissimilarity')
homogeneity = ski.feature.graycoprops(glcm, 'homogeneity')
energy = ski.feature.graycoprops(glcm, 'energy')
ASM = ski.feature.graycoprops(glcm, 'ASM')

print(contrast)
print(dissimilarity)
print(homogeneity)
print(energy)
print(ASM)

ii_tile = ski.transform.integral_image(gray_tile)
haar_coord, haar_featType = ski.feature.haar_like_feature(ii_tile,0,0, width=ii_tile.shape[0], height=ii_tile.shape[1])

"""## Affichages"""

fig,ax = plt.subplots(3,4)
color = 'RdYlBu'
ax[0,0].imshow(tile[:,:,0:3], cmap=color)
ax[0,1].imshow(NDVI, cmap=color)
ax[0,2].imshow(EVI, cmap=color)
ax[0,3].imshow(SAVI, cmap=color)

ax[1,0].imshow(dog, cmap=color)
ax[1,1].imshow(blob_doh, cmap=color)
ax[1,2].imshow(blob_log, cmap=color)
ax[1,3].imshow(canny, cmap="gray")

ax[2,0].imshow(edge_robert, cmap="gray")
ax[2,1].imshow(edge_sobel, cmap="gray")
ax[2,2].imshow(edge_scharr, cmap="gray")
ax[2,3].imshow(edge_prewitt, cmap="gray")

## titles
ax[0,0].title.set_text('original tile')
ax[0,1].title.set_text('NDVI')
ax[0,2].title.set_text('EVI')
ax[0,3].title.set_text('SAVI')

ax[1,0].title.set_text('blob_dog')
ax[1,1].title.set_text('blob_doh')
ax[1,2].title.set_text('blob_log')
ax[1,3].title.set_text('canny')

ax[2,0].title.set_text('edge robert')
ax[2,1].title.set_text('edge sobel')
ax[2,2].title.set_text('edge scharr')
ax[2,3].title.set_text('edge prewitt')

NDVI = NDVI.reshape(1024, 1024, 1)
updated_tile = np.concatenate((tile, NDVI), axis=-1)

updated_tile.shape